import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Shishya Admin Page</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<h1>Shishya Admin Page</h1>
			</main>
		</div>
	)
}

export default Home
